### ISSUE TITLE
is it your first commit at github ever?

### ISSUE THREAD

**Issue by djindjic** [sebmck/ama#13]
https://github.com/babel/babel/commit/c97696c224d718d96848df9e1577f337b45464be
:smile:

**Comment by sebmck** [comment]
Nope! I've actually got a bunch of private/deleted repos. I just made [this](https://github.com/sebmck/amuzor) repo public, it's a content aggregator I worked on with @gabrielecirulli back in late 2012 to early 2013. I also previously worked on a massive full stack web framework that I abandoned and since removed all trace from on the internet.
