### ISSUE TITLE
How do you think we could do open source better?

### ISSUE THREAD

**Issue by sindresorhus** [sebmck/ama#21]

**Comment by sebmck** [comment]
I think in order to do open source better, there really needs to be better tools. IMO GitHub is extremely subpar when it comes to open source management, it just doesn't scale well to large projects. A way to "like" issues as well as filter out the noise (I hate +1s and dumb gifs so much) would be awesome. A way to add descriptions to labels would also be extremely beneficial. I think the community has done an awesome job so far with OSS maintenance but it's extremely tedious and the only way I see that changing is if GitHub steps up their game and releases some features that make it easier for everyone.

**Comment by moretti** [comment]
Here's a Chrome extension that you might find helpful:
https://chrome.google.com/webstore/detail/github-%2B1s/lddfkkebajnpiicnpfamebilmhamkeme/related?hl=en :)

**Comment by sebmck** [comment]
@moretti Yeah I know about that extension. I dislike it heavily because I still get email notifications for each +1 and it's encouraging comment spam.

**Comment by gsklee** [comment]
cc @muan
