### ISSUE TITLE
How do you think your incorporation to Fb will impact Babel

### ISSUE THREAD

**Issue by rafayepes** [sebmck/ama#29]
And congratulations! :D

**Comment by sebmck** [comment]
Thanks! The main impact that you'll see is that there'll be a massive focus on improving stability and performance. It's also likely that you'll see stellar integration with flow to improve compilation output. I'm excited to be able to focus all of my energy and time into it as right now it's been very difficult to balance Babel development and my personal life.

It's unlikely that you'll see the roadmap change that much/at all. I'll still be working on supporting the ecosystems of Ember and Angular, if anything support for them will be much better. It'll also be super excited to get further collaboration from both Facebook engineers and the community in order to make Babel the best tool possible.
