### ISSUE TITLE
What's your favorite city that you've visited so far?

### ISSUE THREAD

**Issue by una** [sebmck/ama#33]
Stories are always fun :smile:

**Comment by sebmck** [comment]
I went to Brussels yesterday. It's the first country/trip I've been on that wasn't conference/company related so it was pretty enjoyable. I walked over 25 kilometres and took photos of a bunch of random buildings which was really fun. I got stuck in a train depot for ~20 minutes though because I got on a train that was at it's last stop and me not knowing any of the local languages didn't understand the announcements.

Here are some photos :blush: 

![a](https://scontent-lhr3-1.xx.fbcdn.net/hphotos-xtp1/v/t1.0-9/12106867_10206322110830529_2962310666485094639_n.jpg?oh=e9fdfbf1eac4a82ee68ffe4af1215765&oe=56A0712F)

![b](https://scontent-lhr3-1.xx.fbcdn.net/hphotos-xta1/v/t1.0-9/12144732_10206322112110561_6186760551700086601_n.jpg?oh=d4e69f030520a3be3b800eeaabd389e1&oe=5691552A)

![c](https://scontent-lhr3-1.xx.fbcdn.net/hphotos-xat1/v/t1.0-9/12074770_10206322112310566_7201345891456269004_n.jpg?oh=789913e9f5438a40f8a9459a177c2c04&oe=56A1F66F)

![d](https://scontent-lhr3-1.xx.fbcdn.net/hphotos-xap1/v/t1.0-9/12118778_10206322109510496_6088585659000044576_n.jpg?oh=a3e5a500bb0f69959be6faa9dcd87422&oe=569FA945)

![e](https://scontent-lhr3-1.xx.fbcdn.net/hphotos-xta1/v/t1.0-9/12144869_10206322110390518_3931220994615318464_n.jpg?oh=c92bf0cc80942546ebb8974db59f563e&oe=56A1CC79)

**Comment by sindresorhus** [comment]
Pics from the train depot please.

**Comment by sebmck** [comment]
I was too busy trying to escape the locked train :( I was super afraid that they were watching me on the cameras and thought I was some hoodlum up rather than some dumb Australian.

**Comment by una** [comment]
Lolol amazing 😝 I was just there two weeks ago!

![image](https://cloud.githubusercontent.com/assets/1693164/10270215/e6d33b5a-6ab8-11e5-86ac-96807a15368d.jpg)

**Comment by sebmck** [comment]
Ohhh nice! I got to the Grand Place super early at like 7:30am so there was barely anyone around.
