### ISSUE TITLE
Are you often confused with Sebastian Markbåge?

### ISSUE THREAD

**Issue by gaearon** [sebmck/ama#39]
Do people often confuse you and @sebmarkbage?
Were there any funny incidents caused by this?

**Comment by sebmck** [comment]
I once got an email that I wasn't supposed to because my email got autofilled when the person typed "Sebastian M". That's probably been the worse. Most of the time it's someone incorrectly messaging/tweeting one of us. I don't really mind anymore. @sebmarkbage isn't a bad person to be confused with :stuck_out_tongue:

**Comment by chenglou** [comment]
I thought sebmck was the other sebastian's new IRC handle at the beginning, so there's that

**Comment by sebmarkbage** [comment]
Aww. Haha. Yea mostly it is autocomplete issues rather than actual confusion.
