### ISSUE TITLE
What's your favorite food?

### ISSUE THREAD

**Issue by HelloImA** [sebmck/ama#9]

**Comment by sebmck** [comment]
[Honey chicken](https://www.google.com/search?site=&tbm=isch&source=hp&biw=1440&bih=729&q=honey+chicken&oq=honey+chicken&gs_l=img.3..0l10.2841.5069.0.5244.21.14.2.2.2.1.156.1098.10j4.14.0....0...1ac.1.64.img..4.17.994.VVIOJxXEhQY), by **far**. It's actually caused me hell because it took me moving out of Australia to find out that it's actually an exclusively Australian Chinese food. I haven't had it in 3 months and it's killing me :cry:

**Comment by coodoo** [comment]
Come to Taipei sometime, you will find a lot of varieties here and the treat is on me :)
